#!/bin/bash

# Cambia la mac de la interfaz WAN y el nombre a un dispositivo AirOS, a partir
# de valores aleatorios.

# 1 - generar mac
# 2 - generar nombre aleatorio
# 3 - escribir configuración en AirOS, salvar y reiniciar


readonly EX_USAGE=64	#command line usage error
readonly EX_DATAERR=65	#data format error
readonly EX_NOINPUT=66	#cannot open input
readonly EX_NOUSER=67	#addressee unknown
readonly EX_NOHOST=68	#host name unknown
readonly EX_UNAVAILABLE=69	#service unavailable
readonly EX_SOFTWARE=70	#internal software error
readonly EX_OSERR=71	#system error (e.g., can't fork)
readonly EX_OSFILE=72	#critical OS file missing
readonly EX_CANTCREAT=73	#can't create (user) output file
readonly EX_IOERR=74	#input/output error
readonly EX_TEMPFAIL=75	#temp failure; user is invited to retry
readonly EX_PROTOCOL=76	#remote error in protocol
readonly EX_NOPERM=77	#permission denied
readonly EX_CONFIG=78	#configuration error

readonly SCRIPT_NAME="${BASH_SOURCE[0]##*\/}"
readonly SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly SCRIPT_VERSION='1.0.0'

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] - Error: $1" >&2
}

#######################################
# Generar una mac
# Arguments:
#   1: ruta completa del archivo oui.txt
# Returns:
#   0: mac generada
#   74: si no se encontró el archivo oui.txt
#######################################
random_mac() {
  local -r ouiFile=$1
  
  if [ ! -f "$ouiFile" ]; then
    err "No se encontró el archivo oui.txt '$ouiFile'" >&2
    exit "$EX_IOERR"
  fi
  
  local -r oui="$(grep -oh  '^[0-9A-Fa-f]\{6\}' "$ouiFile" | shuf -n 1)"
  local -r  random3hex="$(openssl rand -hex 3)"
  
  echo "${oui^^}${random3hex^^}" | sed 's/\(..\)/\1:/g; s/:$//'
}

#######################################
# Generar random {N} character alphanumeric string
# Arguments:
#   1: cantidad de caracteres
#######################################
random_alphanumeric() {
  cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w "${1:-10}" | head -n 1
}

#######################################
# Cambia la configuración en el dispositivo AirOS
#
# Arguments:
#   1: usuario
#   2: ip del dispositivo
#   3: configuración
#  ejemplo: 'netconf.1.hwaddr.mac=B8:07:16:ad:06:34
#            resolv.host.1.name=WOAALHM944'
#   [4: reiniciar dispositivo = 1]
#
# Returns:
# 0: configuración cambiada en dispositivo AirOS
# 65: parámetro no válido
# 69: host AirOS inalcanzable
# 255: acceso ssh a AirOS denegado
#######################################
airos_set_config() {
  local -r user="$1"
  local -r ip="$2"
  local -r config="$3"
  local -r reboot="${4:-1}"
  
  local -r airoscfg='/tmp/system.cfg'
  
  if [ -z "$user" ]; then
    err "el nombre de usuario es obligatorio" >&2
    exit "$EX_DATAERR"
  fi
  if [[ ! "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    err "ip: '${ip}' no válida" >&2
    exit "$EX_DATAERR"
  fi
  if [ -z "$config" ]; then
    err "la configuración es obligatoria" >&2
    exit "$EX_DATAERR"
  fi
  if ! ping -c 1 "$ip" &> /dev/null; then
    err "El dispositivo AirOS con ip: '${ip}' es inalcanzable" >&2
    exit "$EX_UNAVAILABLE"
  fi
  
  local rebootCMD=''
  if [[ "$reboot" -eq 0 ]]; then
    rebootCMD='reboot'
  fi
  

  ssh -T "${user}@${ip}" &> /dev/null <<SSHEOF
  config='$config'
  for keyvalue in \$config; do
    local key="\${keyvalue%%=*}"
    # local value=\${keyvalue##*=}
    sed -i "s/^\${key}=.*/\${keyvalue}/g" "$airoscfg"
  done
  save
  ${rebootCMD}
SSHEOF
  
  local -r ret=$?
  
  if [[ $ret -eq 255 ]]; then
    err "Acceso denegado a '${user}@${ip}'" >&2
    exit $ret
  fi
  
  if [[ $ret -ne 0 ]]; then
    err "A ocurrido un error en '${user}@${ip}', código de error: $ret"
    exit $ret
  fi
}

#######################################
# Cambia la mac de la interfaz WAN y el nombre del dispositivo AirOS
#
# Arguments:
#   1: usuario
#   2: ip del dispositivo
#   3: ruta completa del archivo oui.txt
#   [4: reiniciar dispositivo = 1]
#
# Returns:
# 0:     nombre y mac cambiadas en el dispositivo AirOS
# 1-255: error
#######################################
airos_set_mac_and_name() {
  local -r user="$1"
  local -r ip="$2"
  local -r oui="$3"
  local -r reboot="${4:-1}"
  
  local -r n=10
  local -r mac="$(random_mac "${oui}")"
  local -r name="$(random_alphanumeric "${n}")"
  local -r config="netconf.1.hwaddr.mac=${mac}
  resolv.host.1.name=${name}"
  
  airos_set_config "$user" "$ip" "$config" "$reboot"

  local -r ret=$?
  if [[ $ret ]]; then
    cat <<EOF 
    airmac:${mac}
    airname:${name}
EOF
  fi
}

#######################################
# Muestra la ayuda
#
# Arguments:
#   1: ruta completa por defecto de oui.txt
# Globals:
#   SCRIPT_NAME
# Returns:
#   None
#######################################
usage(){
  cat <<EOF
  ${SCRIPT_NAME}, version ${SCRIPT_VERSION}

  Cambia la mac de la interfaz WAN y el nombre de red a un dispositivo AirOS 
  a partir de valores aleatorios. Si tuvo éxito imprime la nueva mac y el nuevo 
  nombre del dispositivo AirOS

  Requisitos:
  - El dispositivo AirOS debe tener agregada la clave pública del sistema donde
    se ejecuta este script. A continuación se muestra cómo agregadarla al dispositivo:
    1- Descarga la clave pública del dispositivo donde se ejecuta este script a tu PC.
    2- Entra a la interfaz web del dispositivo AirOS 'SERVICES/SSH Server/', toca el 
      botón 'Edit' y agrega la clave pública descargada.
  - Tener habilitada la opción 'Network/WAN Network Settings/MAC Address Cloning'
    en el dispositivo AirOS.

  Uso: ${SCRIPT_NAME} --user john --ip 192.168.0.1 [--reboot] \\
      [--oui ${oui}]

    -h, --help, --ayuda
      muestra la ayuda
    -u, --user, --usuario
      usuario del dispositivo AirOS
    -i, --ip
      ip del dispositivo AirOS
    -o, --oui
      ruta completa del archivo oui.txt
    -r, --reboot, --reiniciar
      reinicia el dispositivo AirOS para aplicar los cambios

  Exit status:
  0: Configuración cambiada en dispositivo AirOS
  65: Parámetro no válido
  69: Host AirOS inalcanzable
  74: No se encontró el archivo oui.txt
  255: Acceso ssh al dispositivo AirOS denegado
EOF
}

main(){
  # random_mac "$OUI_FILE"
  # random_alphanumeric 10
  # local -r config="netconf.1.hwaddr.mac=B8:07:16:ad:06:34
  # resolv.host.1.name=WOAALHM944"
  # airos_set_config "ubnt" "192.168.0.1" "$config"
  
  local PARAMS=""
  local user=''
  local ip=''
  local oui="$SCRIPT_PATH/etc/oui.txt"
  local reboot=1
  
  if [ "$#" -eq 0 ]; then
    eval set -- '-h'
  fi

  while (( "$#" )); do
    case "$1" in
      -u|--user|--usuario)
        user=$2
        shift 2
      ;;
      -i|--ip)
        ip=$2
        shift 2
      ;;
      -o|--oui)
        oui=$2
        shift 2
      ;;
      -r|--reboot|--reiniciar)
        reboot=0
        shift 1
      ;; 
      -h|--help|--ayuda)
        usage "$oui"
        exit 0
      ;;              
      --) # end argument parsing
        shift
        break
      ;;   
      *) # preserve positional arguments
        PARAMS="$PARAMS $1"
        shift
      ;;
    esac
  done
  # set positional arguments in their proper place
  eval set -- "$PARAMS"

  airos_set_mac_and_name "$user" "$ip" "$oui" "$reboot"
}

main "$@"