#!/bin/bash

# Genera una mac y un nombre aleatorio, entra al dispositivo AirOS, cambia la 
# mac, el nombre y lo reinicia.

# 1 - generar mac
# 2 - generar nombre aleatorio
# 3 - escribir configuración en AirOS, salvar y reiniciar


readonly EX_USAGE=64	#command line usage error
readonly EX_DATAERR=65	#data format error
readonly EX_NOINPUT=66	#cannot open input
readonly EX_NOUSER=67	#addressee unknown
readonly EX_NOHOST=68	#host name unknown
readonly EX_UNAVAILABLE=69	#service unavailable
readonly EX_SOFTWARE=70	#internal software error
readonly EX_OSERR=71	#system error (e.g., can't fork)
readonly EX_OSFILE=72	#critical OS file missing
readonly EX_CANTCREAT=73	#can't create (user) output file
readonly EX_IOERR=74	#input/output error
readonly EX_TEMPFAIL=75	#temp failure; user is invited to retry
readonly EX_PROTOCOL=76	#remote error in protocol
readonly EX_NOPERM=77	#permission denied
readonly EX_CONFIG=78	#configuration error


readonly SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly OUI_FILE="$SCRIPT_PATH/etc/oui.txt"

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $1" >&2
}

#######################################
# Generar una mac
# Arguments:
#   1: ruta completa del archivo oui.txt
# Returns:
#   0: mac generada
#   74: si no se encontró el archivo oui.txt
#######################################
random_mac() {
  local ouiFile=$1

  if [ ! -f "$ouiFile" ]; then
    err "No se encontró el archivo oui.txt '$ouiFile'"
    exit "$EX_IOERR"
  fi
  local oui
  local random3
  oui="$(grep -oh  '^[0-9A-Fa-f]\{6\}' "$ouiFile" | shuf -n 1)"
  random3="$(openssl rand -hex 3)"

  echo "${oui}${random3}" | sed 's/\(..\)/\1:/g; s/:$//'
}

#######################################
# Generar random {N} character alphanumeric string
# Arguments:
#   1: cantidad de caracteres
#######################################
random_alphanumeric() {
  cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w "${1:-12}" | head -n 1
}

airos_set_mac_and_name() {
  # IMPLEMENTAR
  return 0
}

main(){
  random_mac "$OUI_FILE"
  random_alphanumeric 10
}

main 